# Generated by Django 4.1.2 on 2022-10-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0002_remove_url_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
