# Generated by Django 4.1.2 on 2022-10-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0003_url_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='pause',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
