# Generated by Django 4.1.2 on 2022-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0004_alter_url_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='interval',
            field=models.IntegerField(default=1, help_text='in minutes'),
        ),
    ]
