# Generated by Django 4.1.2 on 2022-10-29 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0005_alter_url_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='interval',
            field=models.PositiveIntegerField(default=1, help_text='in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
